name: Deploy DNS to Cloudflare

on:
  push:
    branches:
      - main
    paths:
      - 'infra/cloudflare/**'
      - '.github/workflows/deploy-dns.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    
    environment:
      name: cloudflare-production
      url: 'https://${{ vars.DOMAIN_NAME }}'

    env:
      TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    defaults:
      run:
        working-directory: ./infra/cloudflare

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color